spring:
  jpa:
    database: mysql
    show-sql: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/saas?characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
    username: root
    password: '123456'
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000
      pool-name: TinyUrlHikari
      maximum-pool-size: 20
com:
  tinyurl:
    read-time-out: 3600
    write-time-out: 3600
    tiny-host: http://127.0.0.1:8080
    tiny-url-redis:
      database: 12
      host: 127.0.0.1
      port: 6379
      password: "123456"
      lettuce:
        pool:
          max-active: 20
          max-idle: 8
          max-wait: 5000ms
          min-idle: 1
      timeout: 30s